import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'it';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    'nav.home': 'Home',
    'nav.dashboard': 'Dashboard',
    'nav.signin': 'Sign In with Google',
    'nav.signout': 'Sign Out',
    'home.hero.title': 'Find your next job.',
    'home.hero.subtitle': 'Search millions of jobs from thousands of job boards, newspapers, classifieds and company websites.',
    'home.search.placeholder': 'Job title, keywords, or company',
    'home.location.placeholder': 'City, state, or zip',
    'home.search.button': 'Search Jobs',
    'home.search.searching': 'Searching...',
    'home.filters.show': 'Advanced filters',
    'home.filters.hide': 'Hide advanced filters',
    'home.filters.contract.any': 'Any Contract Type',
    'home.filters.contract.permanent': 'Permanent',
    'home.filters.contract.contract': 'Contract',
    'home.filters.contract.temp': 'Temporary',
    'home.filters.contract.internship': 'Internship/Training',
    'home.filters.contract.volunteer': 'Volunteer',
    'home.filters.hours.any': 'Any Work Hours',
    'home.filters.hours.full': 'Full-time',
    'home.filters.hours.part': 'Part-time',
    'home.filters.sort.relevance': 'Sort by Relevance',
    'home.filters.sort.date': 'Sort by Date',
    'home.filters.sort.salary': 'Sort by Salary',
    'home.results.showing': 'Showing',
    'home.results.of': 'of',
    'home.results.jobs': 'jobs',
    'home.empty.title': 'Ready for your next role?',
    'home.empty.subtitle': 'Enter a job title or location above to start searching.',
    'home.page': 'Page',
    'job.save': 'Save Job',
    'job.saved': 'Saved',
    'job.share': 'Share',
    'job.details': 'View Details',
    'job.apply': 'Apply Now',
    'job.description': 'Job Description',
    'dashboard.title': 'My Dashboard',
    'dashboard.subtitle': 'Manage your saved jobs and track your applications.',
    'dashboard.saved_jobs': 'Saved Jobs',
    'dashboard.empty.title': 'No saved jobs yet',
    'dashboard.empty.subtitle': 'Jobs you save will appear here. Start searching to find your next opportunity.',
    'dashboard.empty.action': 'Find Jobs',
    'dashboard.remove': 'Remove',
    'dashboard.stats.saved': 'Saved Jobs',
    'dashboard.stats.applications': 'Applications',
    'dashboard.stats.interviews': 'Interviews',
    'dashboard.settings': 'Settings',
    'dashboard.backup': 'Backup Data',
    'dashboard.alert.auth': 'Please sign in to view your dashboard',
    'error.signin': 'Please sign in to save jobs.',
    'error.apply_signin': 'Please sign in to apply for this job.',
    'error.search': 'Failed to search jobs. Please try again.',
    'error.search_title': 'Search Error',
    'error.multiple_locations': 'Multiple locations found',
    'error.select_location': 'Please select the specific location you meant:',
    'dashboard.cv': 'My CV',
    'cv.title': 'Curriculum Vitae',
    'cv.subtitle': 'Update your resume to apply for jobs faster.',
    'cv.summary': 'Professional Summary',
    'cv.summary_placeholder': 'A brief summary of your professional background...',
    'cv.experience': 'Experience',
    'cv.experience_placeholder': 'Your work experience...',
    'cv.education': 'Education',
    'cv.education_placeholder': 'Your educational background...',
    'cv.skills': 'Skills',
    'cv.skills_placeholder': 'e.g., React, TypeScript, Node.js',
    'cv.save': 'Save CV',
    'cv.saving': 'Saving...',
    'cv.saved': 'CV saved successfully!',
    'dashboard.admin_banners': 'Banners (Admin)',
    'admin.title': 'Banner Management',
    'admin.add_new': 'Add New Banner / Ad Unit',
    'admin.type.image': 'Image Banner',
    'admin.type.adsense': 'Google AdSense',
    'admin.image_url': 'Image URL',
    'admin.link_url': 'Link URL (Optional)',
    'admin.adsense_client': 'AdSense Publisher ID (Client)',
    'admin.adsense_slot': 'AdSense Slot ID (Slot)',
    'admin.ad_format': 'Ad Format',
    'admin.full_width': 'Full Width Responsive',
    'admin.preview': 'Configuration Preview',
    'admin.active': 'Active / Visible on site',
    'admin.button.add': 'Add Banner Unit',
    'admin.button.saving': 'Saving...',
    'admin.existing': 'Existing Banners & Ad Units',
    'admin.no_banners': 'No banners found.',
    'admin.backup_desc': 'Your data is automatically synced to Firestore. You can also trigger a manual backup.',
    'admin.backup_btn': 'Export Data to Cloud',
    'dashboard.analytics.saved': 'Saved Jobs',
    'dashboard.analytics.applications': 'Applications Sent',
    'dashboard.analytics.interviews': 'Interviews',
    'dashboard.settings.biometric': 'Biometric Authentication',
    'dashboard.settings.biometric_desc': 'Use Touch ID or Face ID for login',
    'dashboard.settings.alerts_new': 'New job alerts matching saved searches',
    'dashboard.settings.alerts_status': 'Application status updates',
    'dashboard.settings.active': 'Active',
    'dashboard.settings.notifications': 'Notification Preferences',
    'dashboard.settings.security': 'Security',
    'dashboard.settings.data': 'Data & Privacy',
    'dashboard.analytics': 'Analytics',
    'dashboard.settings_tab': 'Settings',
  },
  it: {
    'nav.home': 'Home',
    'nav.dashboard': 'Bacheca',
    'nav.signin': 'Accedi con Google',
    'nav.signout': 'Esci',
    'home.hero.title': 'Trova il tuo prossimo lavoro.',
    'home.hero.subtitle': 'Cerca milioni di lavori da migliaia di bacheche di lavoro, giornali, annunci e siti web aziendali.',
    'home.search.placeholder': 'Titolo del lavoro, parole chiave o azienda',
    'home.location.placeholder': 'Città, stato o cap',
    'home.search.button': 'Cerca Lavoro',
    'home.search.searching': 'Ricerca in corso...',
    'home.filters.show': 'Filtri avanzati',
    'home.filters.hide': 'Nascondi filtri avanzati',
    'home.filters.contract.any': 'Qualsiasi contratto',
    'home.filters.contract.permanent': 'A tempo indeterminato',
    'home.filters.contract.contract': 'A contratto',
    'home.filters.contract.temp': 'Temporaneo',
    'home.filters.contract.internship': 'Stage/Tirocinio',
    'home.filters.contract.volunteer': 'Volontariato',
    'home.filters.hours.any': 'Qualsiasi orario',
    'home.filters.hours.full': 'Tempo pieno',
    'home.filters.hours.part': 'Part-time',
    'home.filters.sort.relevance': 'Ordina per Rilevanza',
    'home.filters.sort.date': 'Ordina per Data',
    'home.filters.sort.salary': 'Ordina per Stipendio',
    'home.results.showing': 'Visualizzati',
    'home.results.of': 'di',
    'home.results.jobs': 'lavori',
    'home.empty.title': 'Pronto per il tuo prossimo ruolo?',
    'home.empty.subtitle': 'Inserisci un titolo o una posizione qui sopra per iniziare a cercare.',
    'home.page': 'Pagina',
    'job.save': 'Salva',
    'job.saved': 'Salvato',
    'job.share': 'Condividi',
    'job.details': 'Dettagli',
    'job.apply': 'Candidati Ora',
    'job.description': 'Descrizione del lavoro',
    'dashboard.title': 'La mia bacheca',
    'dashboard.subtitle': 'Gestisci i tuoi lavori salvati e monitora le tue candidature.',
    'dashboard.saved_jobs': 'Lavori Salvati',
    'dashboard.empty.title': 'Nessun lavoro salvato',
    'dashboard.empty.subtitle': 'I lavori che salvi appariranno qui. Inizia a cercare per trovare la tua prossima opportunità.',
    'dashboard.empty.action': 'Trova Lavoro',
    'dashboard.remove': 'Rimuovi',
    'dashboard.stats.saved': 'Lavori Salvati',
    'dashboard.stats.applications': 'Candidature',
    'dashboard.stats.interviews': 'Colloqui',
    'dashboard.settings': 'Impostazioni',
    'dashboard.backup': 'Backup Dati',
    'dashboard.alert.auth': 'Accedi per visualizzare la tua bacheca',
    'error.signin': 'Accedi per salvare i lavori.',
    'error.apply_signin': 'Registrati o accedi per candidarti a questa offerta.',
    'error.search': 'Ricerca fallita. Riprova.',
    'error.search_title': 'Errore di Ricerca',
    'error.multiple_locations': 'Trovate più località',
    'error.select_location': 'Seleziona la località specifica che intendevi:',
    'dashboard.cv': 'Il mio CV',
    'cv.title': 'Curriculum Vitae',
    'cv.subtitle': 'Aggiorna il tuo CV per candidarti più velocemente.',
    'cv.summary': 'Profilo Professionale',
    'cv.summary_placeholder': 'Un breve riassunto del tuo background professionale...',
    'cv.experience': 'Esperienza Lavorativa',
    'cv.experience_placeholder': 'La tua esperienza lavorativa...',
    'cv.education': 'Formazione',
    'cv.education_placeholder': 'Il tuo percorso di studi...',
    'cv.skills': 'Competenze',
    'cv.skills_placeholder': 'es. React, TypeScript, Node.js',
    'cv.save': 'Salva CV',
    'cv.saving': 'Salvataggio in corso...',
    'cv.saved': 'CV salvato con successo!',
    'dashboard.admin_banners': 'Banners (Admin)',
    'admin.title': 'Gestione Banner',
    'admin.add_new': 'Aggiungi Nuovo Banner / Unità Ad',
    'admin.type.image': 'Immagine Banner',
    'admin.type.adsense': 'Google AdSense',
    'admin.image_url': 'URL Immagine',
    'admin.link_url': 'URL Collegamento (Opzionale)',
    'admin.adsense_client': 'AdSense Publisher ID (Client)',
    'admin.adsense_slot': 'AdSense Slot ID (Slot)',
    'admin.ad_format': 'Formato Ad',
    'admin.full_width': 'Larghezza Intera (Responsivo)',
    'admin.preview': 'Anteprima Configurazione',
    'admin.active': 'Attivo / Visibile sul sito',
    'admin.button.add': 'Aggiungi Unità Banner',
    'admin.button.saving': 'Salvataggio...',
    'admin.existing': 'Banner e Unità Ad Esistenti',
    'admin.no_banners': 'Nessun banner trovato.',
    'admin.backup_desc': 'I tuoi dati sono sincronizzati automaticamente su Firestore. Puoi anche avviare un backup manuale.',
    'admin.backup_btn': 'Esporta Dati nel Cloud',
    'dashboard.analytics.saved': 'Lavori Salvati',
    'dashboard.analytics.applications': 'Candidature Inviate',
    'dashboard.analytics.interviews': 'Colloqui',
    'dashboard.settings.biometric': 'Autenticazione Biometrica',
    'dashboard.settings.biometric_desc': 'Usa Touch ID o Face ID per accedere',
    'dashboard.settings.alerts_new': 'Avvisi per nuovi lavori dalle ricerche salvate',
    'dashboard.settings.alerts_status': 'Aggiornamenti stato candidature',
    'dashboard.settings.active': 'Attivo',
    'dashboard.settings.notifications': 'Preferenze Notifiche',
    'dashboard.settings.security': 'Sicurezza',
    'dashboard.settings.data': 'Dati e Privacy',
    'dashboard.analytics': 'Analitiche',
    'dashboard.settings_tab': 'Impostazioni',
  }
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('app_language');
    if (saved === 'en' || saved === 'it') return saved;
    const browserLang = navigator.language.split('-')[0];
    return 'it';
  });

  useEffect(() => {
    localStorage.setItem('app_language', language);
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
